name: Notify Discord on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Notify merged pull request
        shell: bash
        run: |
          actor='${{ github.event.pull_request.merged_by.login }}'
          source_branch='${{ github.event.pull_request.head.ref }}'
          target_branch='${{ github.event.pull_request.base.ref }}'
          title='${{ github.event.pull_request.title }}'
          number='${{ github.event.pull_request.number }}'
          merged_time='${{ github.event.pull_request.merged_at }}'

          formatted_time=$(TZ=Asia/Tokyo date -d "$merged_time" "+%Y年%m月%d日%H:%M:%S")

          content="# 🔀 GitHubにマージされました！"
          content="$content\n> 🌿 **$source_branch → $target_branch**"
          content="$content\n> ## 👤 by $actor"
          content="$content\n> **🕒 $formatted_time**"
          content="$content\n> 💬 PR #$number"
          content="$content\n> 📝 $title"

          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\":\"$(printf '%b' "$content")\"}" \
            "${{ secrets.DISCORD_WEBHOOK }}"